import { Roboto } from "next/font/google";
import StyledComponentsRegistry from "./registry";
import { Providers } from "./providers";
import { TranslationContextProvider } from "@/context/TranslationContext";

const roboto = Roboto({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Portfólio Mateus Cury",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <TranslationContextProvider>
          <StyledComponentsRegistry>
            <Providers>{children}</Providers>
          </StyledComponentsRegistry>
        </TranslationContextProvider>
      </body>
    </html>
  );
}
